version: '3'

services:
    app:
        build: .
        #image: marceloarevalos/webbapp
        environment:
            MONGO_URL: "mongodb://db/test"
        depends_on:
            - db
        ports:
            - "8080:3000"
        db:
            image: mongo
